[[prereqs]]
name = "vcredist-2019-x64"

[[actions]]
name = "play"
path = "studio.exe"

[[actions]]
name = "Documentation"
path = "https://github.com/nem0/lumixengine/wiki"

[[actions]]
name = "Source code"
path = "https://github.com/nem0/lumixengine"

[[actions]]
name = "Video tutorials"
path = "https://www.youtube.com/watch?v=5ljk2myprno&list=PLmpj2nDGsFkQfPBC12XYGAyCL8IJ4WbQO"