version: 0.21.{build}
os: Windows Server 2012 R2
configuration: RelWithDebInfo
before_build:
  - cd projects
  - genie_vs13.bat
  - cd ..
build:
  project: projects\tmp\vs2013\LumixEngine.sln
  verbosity: minimal
test_script:
- ps: >-
    git clone --depth=1  https://github.com/nem0/LumixEngine_data.git 2>&1 | % { $_.ToString() } 

    cd LumixEngine_data

    & "..\projects\tmp\vs2013\bin\RelWithDebInfo\unit_tests.exe" | Write-Output

    $wc = New-Object Net.WebClient
            $url = "https://ci.appveyor.com/api/testresults/nunit/$Env:APPVEYOR_JOB_ID"
            $wc.UploadFile($url, (Resolve-Path .\tests.xml))

- ps: >-
    & "..\projects\tmp\vs2013\bin\RelWithDebInfo\studio.exe" -run_script render_tests/main.lua | Write-Output

- ps: >-
    & "..\projects\tmp\vs2013\bin\RelWithDebInfo\studio.exe" -run_script unit_tests/editor/main.lua | Write-Output

- ps: >-
    & "..\projects\tmp\vs2013\bin\RelWithDebInfo\render_test.exe" | Write-Output

after_build:
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\animation.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\audio.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\editor.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\engine.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\lua_script.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\physics.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\renderer.dll
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\studio.exe
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\animation.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\audio.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\editor.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\engine.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\lua_script.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\physics.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\renderer.pdb
 - 7z a lumix.zip %APPVEYOR_BUILD_FOLDER%\projects\tmp\vs2013\bin\RelWithDebInfo\studio.pdb
 
artifacts:
- path: tests.xml
  name: tests.xml
  
- path: lumix.zip
  name: lumix.zip

